// Elites (§11.8): combates duros con un mini-modificador (mas leve que un jefe) y reliquia
// garantizada al ganar. Reutilizan BossDef con elite:true (excluidas del pool de jefes).
import type { BossDef } from '@umbral/engine';

export const ELITES: BossDef[] = [
  {
    id: 'elite.sabueso_seco',
    name: 'Sabueso Seco',
    sima: 1,
    elite: true,
    lore: 'Olfatea el descarte.',
    tell: 'Jadeo seco.',
    orla: 'Pelaje ralo.',
    modifier: { discardsDelta: -1 },
  },
  {
    id: 'elite.guardian_avido',
    name: 'Guardian Avido',
    sima: 1,
    elite: true,
    lore: 'Cobra mas alto.',
    tell: 'Mirada codiciosa.',
    orla: 'Garras.',
    modifier: { objectiveFactor: 1.2 },
  },
  {
    id: 'elite.sanguijuela_mayor',
    name: 'Sanguijuela Mayor',
    sima: 2,
    elite: true,
    lore: 'Te drena en cada jugada.',
    tell: 'Succion.',
    orla: 'Ventosas.',
    modifier: { sanityPerHand: 2 },
  },
  {
    id: 'elite.mordaza',
    name: 'Mordaza',
    sima: 2,
    elite: true,
    lore: 'Te deja una mano menos.',
    tell: 'Tela en la boca.',
    orla: 'Nudos.',
    modifier: { handsDelta: -1 },
  },
  {
    id: 'elite.encanecido',
    name: 'El Encanecido',
    sima: 2,
    elite: true,
    lore: 'Las figuras pierden fuerza.',
    tell: 'Canas.',
    orla: 'Polvo.',
    modifier: { figuresHalf: true },
  },
  {
    id: 'elite.amordazado',
    name: 'El Amordazado',
    sima: 3,
    elite: true,
    lore: 'Silencia un palo.',
    tell: 'Boca cosida.',
    orla: 'Hilo.',
    modifier: { silenceSuits: ['LLAVE'] },
  },
  {
    id: 'elite.recaudador',
    name: 'El Recaudador',
    sima: 3,
    elite: true,
    lore: 'Te cobra por jugar.',
    tell: 'Cuenta monedas.',
    orla: 'Cadenas de oro.',
    modifier: { coinsPerHand: 3 },
  },
  {
    id: 'elite.reflejo_turbio',
    name: 'Reflejo Turbio',
    sima: 3,
    elite: true,
    lore: 'Empana tus multiplicadores.',
    tell: 'Espejo sucio.',
    orla: 'Vaho.',
    modifier: { relicXMultPenalty: 0.25 },
  },
  {
    id: 'elite.carcoma_menor',
    name: 'Carcoma Menor',
    sima: 2,
    elite: true,
    lore: 'Mordisquea tu mazo.',
    tell: 'Crujidos.',
    orla: 'Serrin.',
    modifier: { destroyDeckAtStart: 1 },
  },
  {
    id: 'elite.centinela',
    name: 'Centinela',
    sima: 3,
    elite: true,
    lore: 'Mas alto, mas duro.',
    tell: 'No parpadea.',
    orla: 'Ojos fijos.',
    modifier: { objectiveFactor: 1.15 },
  },
];
