// Reliquias generales como DATA + efectos declarativos (§11.1). Bloque 5: ~25 representativas,
// una(s) por arquetipo (§13.4), para probar el DSL. Las 60 completas llegan en el Bloque 9.
import type { RelicDef } from '@umbral/engine';

export const GENERAL_RELICS: RelicDef[] = [
  // ---- Mult plano (§11.1.a) ----
  {
    id: 'relic.catalizador',
    name: 'Catalizador',
    rarity: 'comun',
    cost: 4,
    flavor: 'Una gota basta para que todo prenda.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 4 }],
  },
  {
    id: 'relic.letania',
    name: 'Letania',
    rarity: 'comun',
    cost: 4,
    flavor: 'Cada palabra repetida pesa mas que la anterior.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 1, per: 'playedCards' }],
  },
  {
    id: 'relic.tridente',
    name: 'Tridente',
    rarity: 'comun',
    cost: 4,
    flavor: 'Tres puntas, una herida.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 12, when: { type: 'exactlyCards', count: 3 } }],
  },
  {
    id: 'relic.mano_abierta',
    name: 'Mano Abierta',
    rarity: 'comun',
    cost: 4,
    flavor: 'Lo que retienes tambien cuenta.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 2, per: 'cardsInHandNotPlayed' }],
  },
  {
    id: 'relic.brasa',
    name: 'Brasa',
    rarity: 'comun',
    cost: 4,
    flavor: 'El primer rescoldo es el mas vivo.',
    tags: ['mult'],
    onHandPlayed: [
      { kind: 'addMult', n: 3 },
      { kind: 'addMult', n: 1, when: { type: 'firstHand' } },
    ],
  },
  {
    id: 'relic.yesca',
    name: 'Yesca',
    rarity: 'comun',
    cost: 4,
    flavor: 'Seca de cordura, arde mejor.',
    tags: ['mult', 'cordura'],
    onHandPlayed: [
      { kind: 'addMult', n: 4 },
      { kind: 'addMult', n: 2, when: { type: 'sanityBelow', value: 70 } },
    ],
  },

  // ---- Fichas plano (§11.1.b) ----
  {
    id: 'relic.lastre_de_plomo',
    name: 'Lastre de Plomo',
    rarity: 'comun',
    cost: 4,
    flavor: 'Hunde la mano, hunde el objetivo.',
    tags: ['fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 50 }],
  },
  {
    id: 'relic.reliquia_del_avaro',
    name: 'Reliquia del Avaro',
    rarity: 'comun',
    cost: 4,
    flavor: 'Cuenta tus monedas; ellas te cuentan a ti.',
    tags: ['fichas', 'economia'],
    onHandPlayed: [{ kind: 'addFichas', n: 2, per: 'gold', max: 100 }],
  },
  {
    id: 'relic.costra',
    name: 'Costra',
    rarity: 'comun',
    cost: 4,
    flavor: 'Lo que cubre la herida tambien la alimenta.',
    tags: ['fichas'],
    onHandPlayed: [
      { kind: 'addFichas', n: 20 },
      { kind: 'addFichas', n: 20, when: { type: 'handHasFigure' } },
    ],
  },

  // ---- Condicionales por palo (§11.1.c) ----
  {
    id: 'relic.osario_mayor',
    name: 'Osario Mayor',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Cada hueso recuerda su numero.',
    tags: ['fichas', 'mult', 'palo'],
    onCardScored: [
      { kind: 'addFichas', n: 20, when: { type: 'suit', suit: 'HUESO' } },
      { kind: 'addMult', n: 1, when: { type: 'suit', suit: 'HUESO' } },
    ],
  },
  {
    id: 'relic.corazon_negro',
    name: 'Corazon Negro',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Late por lo que no deberia.',
    tags: ['mult', 'palo'],
    onCardScored: [{ kind: 'addMult', n: 3, when: { type: 'suit', suit: 'CALIZ' } }],
  },
  {
    id: 'relic.cerrajero',
    name: 'Cerrajero',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Toda puerta cede al numero correcto.',
    tags: ['fichas', 'palo'],
    onCardScored: [{ kind: 'addFichas', n: 25, when: { type: 'suit', suit: 'LLAVE' } }],
  },
  {
    id: 'relic.vigia',
    name: 'Vigia',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'No parpadea. Nunca.',
    tags: ['mult', 'palo'],
    onCardScored: [{ kind: 'addMult', n: 4, when: { type: 'suit', suit: 'OJO' } }],
  },

  // ---- Condicionales por tipo de mano (§11.1.d) ----
  {
    id: 'relic.gemelo',
    name: 'Gemelo',
    rarity: 'comun',
    cost: 5,
    flavor: 'Lo que viene en pares, manda.',
    tags: ['mult'],
    onHandPlayed: [
      { kind: 'addMult', n: 8, when: { type: 'handType', any: ['pareja', 'doble_pareja'] } },
    ],
  },
  {
    id: 'relic.vitral',
    name: 'Vitral',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Un solo color, mil esquirlas.',
    tags: ['fichas', 'mult'],
    onHandPlayed: [
      { kind: 'addFichas', n: 30, when: { type: 'handType', any: ['color'] } },
      { kind: 'addMult', n: 4, when: { type: 'handType', any: ['color'] } },
    ],
  },
  {
    id: 'relic.monarca',
    name: 'Monarca',
    rarity: 'rara',
    cost: 10,
    flavor: 'Solo se inclina ante las grandes manos.',
    tags: ['xmult'],
    xMult: [
      {
        kind: 'xMult',
        factor: 2,
        when: { type: 'handType', any: ['full', 'poker', 'escalera_color', 'escalera_real'] },
      },
    ],
  },

  // ---- Composicion / rango (§11.1.e) ----
  {
    id: 'relic.corte_real',
    name: 'Corte Real',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'La corte cobra entrada.',
    tags: ['fichas'],
    onCardScored: [{ kind: 'addFichas', n: 30, when: { type: 'isFace' } }],
  },
  {
    id: 'relic.cuatro_palos',
    name: 'Cuatro Palos',
    rarity: 'rara',
    cost: 10,
    flavor: 'Caliz, llave, hueso y ojo: el pacto entero.',
    tags: ['fichas', 'mult'],
    onHandPlayed: [
      { kind: 'addFichas', n: 60, when: { type: 'allFourSuits' } },
      { kind: 'addMult', n: 15, when: { type: 'allFourSuits' } },
    ],
  },

  // ---- Retrigger (§11.1.f) ----
  {
    id: 'relic.reverberacion',
    name: 'Reverberacion',
    rarity: 'rara',
    cost: 9,
    flavor: 'Las figuras hablan dos veces.',
    tags: ['retrigger'],
    retrigger: { when: { type: 'isFace' }, times: 1 },
  },
  {
    id: 'relic.camara_de_ecos',
    name: 'Camara de Ecos',
    rarity: 'rara',
    cost: 10,
    flavor: 'Lo grabado resuena.',
    tags: ['retrigger'],
    retrigger: { when: { type: 'hasEnhancement' }, times: 1 },
  },

  // ---- ×Multiplicador (§11.1.g) ----
  {
    id: 'relic.espejo_negro',
    name: 'Espejo Negro',
    rarity: 'rara',
    cost: 10,
    flavor: 'Refleja mas de lo que muestras.',
    tags: ['xmult'],
    xMult: [{ kind: 'xMult', factor: 1.5 }],
  },
  {
    id: 'relic.eclipse',
    name: 'Eclipse',
    rarity: 'rara',
    cost: 10,
    flavor: 'Apaga el mult, enciende las fichas.',
    tags: ['xmult', 'fichas'],
    xMult: [
      { kind: 'xMult', factor: 0.5 },
      { kind: 'xFichas', factor: 2 },
    ],
  },
  {
    id: 'relic.sistole',
    name: 'Sistole',
    rarity: 'rara',
    cost: 9,
    flavor: 'El primer latido lo es todo.',
    tags: ['xmult'],
    xMult: [{ kind: 'xMult', factor: 3, when: { type: 'firstHand' } }],
  },
  {
    id: 'relic.luna_sangrante',
    name: 'Luna Sangrante',
    rarity: 'rara',
    cost: 9,
    flavor: 'Crece cuando la razon mengua.',
    tags: ['xmult', 'cordura'],
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'sanityBelow', value: 50 } }],
  },
  {
    id: 'relic.convergencia',
    name: 'Convergencia',
    rarity: 'rara',
    cost: 11,
    flavor: 'Cuanto mas se juntan, mas se multiplican.',
    tags: ['xmult'],
    xMult: [{ kind: 'xMult', factor: 1, perStep: { per: 'xmultRelics', step: 0.25 } }],
  },

  // ---- Escaladoras (§11.1.h) ----
  {
    id: 'relic.sanguijuela',
    name: 'Sanguijuela',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Cada pareja la engorda.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'handPlayed', handType: 'pareja' }, add: 1, as: 'mult' },
  },
  {
    id: 'relic.gloton',
    name: 'Gloton',
    rarity: 'rara',
    cost: 9,
    flavor: 'Nunca tiene suficiente.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'cardScored' }, add: 3, as: 'fichas' },
  },
  {
    id: 'relic.vendetta',
    name: 'Vendetta',
    rarity: 'rara',
    cost: 10,
    flavor: 'Cada jefe caido alimenta la siguiente.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'bossDefeated' }, add: 4, as: 'mult' },
  },

  // ---- Cambia-motor (§11.1.i) ----
  {
    id: 'relic.tercera_mano',
    name: 'Tercera Mano',
    rarity: 'rara',
    cost: 10,
    flavor: 'Una mano mas para lo que no se nombra.',
    tags: ['utilidad'],
    modifyCombat: { hands: 1 },
  },
  {
    id: 'relic.quinta_carta',
    name: 'Quinta Carta',
    rarity: 'rara',
    cost: 10,
    flavor: 'Siempre hay sitio para una mas.',
    tags: ['utilidad'],
    modifyCombat: { handSize: 1 },
  },
];
