// Las 60 reliquias generales como DATA + efectos declarativos (§11.1). Cada arquetipo (§13.4)
// tiene apoyos. Cero `if`-por-id en el engine: todo se interpreta desde estos objetos (§5.4).
import type { RelicDef } from '@umbral/engine';

export const GENERAL_RELICS: RelicDef[] = [
  // ---- Mult plano (§11.1.a) ----
  {
    id: 'relic.catalizador',
    name: 'Catalizador',
    rarity: 'comun',
    cost: 4,
    flavor: 'Una gota basta para que todo prenda.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 4 }],
  },
  {
    id: 'relic.letania',
    name: 'Letania',
    rarity: 'comun',
    cost: 4,
    flavor: 'Cada palabra repetida pesa mas que la anterior.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 1, per: 'playedCards' }],
  },
  {
    id: 'relic.tridente',
    name: 'Tridente',
    rarity: 'comun',
    cost: 4,
    flavor: 'Tres puntas, una herida.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 12, when: { type: 'exactlyCards', count: 3 } }],
  },
  {
    id: 'relic.mano_abierta',
    name: 'Mano Abierta',
    rarity: 'comun',
    cost: 4,
    flavor: 'Lo que retienes tambien cuenta.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 2, per: 'cardsInHandNotPlayed' }],
  },
  {
    id: 'relic.brasa',
    name: 'Brasa',
    rarity: 'comun',
    cost: 4,
    flavor: 'El primer rescoldo es el mas vivo.',
    tags: ['mult'],
    onHandPlayed: [
      { kind: 'addMult', n: 3 },
      { kind: 'addMult', n: 1, when: { type: 'firstHand' } },
    ],
  },
  {
    id: 'relic.yesca',
    name: 'Yesca',
    rarity: 'comun',
    cost: 4,
    flavor: 'Seca de cordura, arde mejor.',
    tags: ['mult', 'cordura'],
    onHandPlayed: [
      { kind: 'addMult', n: 4 },
      { kind: 'addMult', n: 2, when: { type: 'sanityBelow', value: 70 } },
    ],
  },

  // ---- Fichas plano (§11.1.b) ----
  {
    id: 'relic.lastre_de_plomo',
    name: 'Lastre de Plomo',
    rarity: 'comun',
    cost: 4,
    flavor: 'Hunde la mano, hunde el objetivo.',
    tags: ['fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 50 }],
  },
  {
    id: 'relic.reliquia_del_avaro',
    name: 'Reliquia del Avaro',
    rarity: 'comun',
    cost: 4,
    flavor: 'Cuenta tus monedas; ellas te cuentan a ti.',
    tags: ['fichas', 'economia'],
    onHandPlayed: [{ kind: 'addFichas', n: 2, per: 'gold', max: 100 }],
  },
  {
    id: 'relic.costra',
    name: 'Costra',
    rarity: 'comun',
    cost: 4,
    flavor: 'Lo que cubre la herida tambien la alimenta.',
    tags: ['fichas'],
    onHandPlayed: [
      { kind: 'addFichas', n: 20 },
      { kind: 'addFichas', n: 20, when: { type: 'handHasFigure' } },
    ],
  },

  // ---- Condicionales por palo (§11.1.c) ----
  {
    id: 'relic.osario_mayor',
    name: 'Osario Mayor',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Cada hueso recuerda su numero.',
    tags: ['fichas', 'mult', 'palo'],
    onCardScored: [
      { kind: 'addFichas', n: 20, when: { type: 'suit', suit: 'HUESO' } },
      { kind: 'addMult', n: 1, when: { type: 'suit', suit: 'HUESO' } },
    ],
  },
  {
    id: 'relic.corazon_negro',
    name: 'Corazon Negro',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Late por lo que no deberia.',
    tags: ['mult', 'palo'],
    onCardScored: [{ kind: 'addMult', n: 3, when: { type: 'suit', suit: 'CALIZ' } }],
  },
  {
    id: 'relic.cerrajero',
    name: 'Cerrajero',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Toda puerta cede al numero correcto.',
    tags: ['fichas', 'palo'],
    onCardScored: [{ kind: 'addFichas', n: 25, when: { type: 'suit', suit: 'LLAVE' } }],
  },
  {
    id: 'relic.vigia',
    name: 'Vigia',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'No parpadea. Nunca.',
    tags: ['mult', 'palo'],
    onCardScored: [{ kind: 'addMult', n: 4, when: { type: 'suit', suit: 'OJO' } }],
  },

  // ---- Condicionales por tipo de mano (§11.1.d) ----
  {
    id: 'relic.gemelo',
    name: 'Gemelo',
    rarity: 'comun',
    cost: 5,
    flavor: 'Lo que viene en pares, manda.',
    tags: ['mult'],
    onHandPlayed: [
      { kind: 'addMult', n: 8, when: { type: 'handType', any: ['pareja', 'doble_pareja'] } },
    ],
  },
  {
    id: 'relic.vitral',
    name: 'Vitral',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Un solo color, mil esquirlas.',
    tags: ['fichas', 'mult'],
    onHandPlayed: [
      { kind: 'addFichas', n: 30, when: { type: 'handType', any: ['color'] } },
      { kind: 'addMult', n: 4, when: { type: 'handType', any: ['color'] } },
    ],
  },
  {
    id: 'relic.monarca',
    name: 'Monarca',
    rarity: 'rara',
    cost: 10,
    flavor: 'Solo se inclina ante las grandes manos.',
    tags: ['xmult'],
    xMult: [
      {
        kind: 'xMult',
        factor: 2,
        when: { type: 'handType', any: ['full', 'poker', 'escalera_color', 'escalera_real'] },
      },
    ],
  },

  // ---- Composicion / rango (§11.1.e) ----
  {
    id: 'relic.corte_real',
    name: 'Corte Real',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'La corte cobra entrada.',
    tags: ['fichas'],
    onCardScored: [{ kind: 'addFichas', n: 30, when: { type: 'isFace' } }],
  },
  {
    id: 'relic.cuatro_palos',
    name: 'Cuatro Palos',
    rarity: 'rara',
    cost: 10,
    flavor: 'Caliz, llave, hueso y ojo: el pacto entero.',
    tags: ['fichas', 'mult'],
    onHandPlayed: [
      { kind: 'addFichas', n: 60, when: { type: 'allFourSuits' } },
      { kind: 'addMult', n: 15, when: { type: 'allFourSuits' } },
    ],
  },

  // ---- Retrigger (§11.1.f) ----
  {
    id: 'relic.reverberacion',
    name: 'Reverberacion',
    rarity: 'rara',
    cost: 9,
    flavor: 'Las figuras hablan dos veces.',
    tags: ['retrigger'],
    retrigger: { when: { type: 'isFace' }, times: 1 },
  },
  {
    id: 'relic.camara_de_ecos',
    name: 'Camara de Ecos',
    rarity: 'rara',
    cost: 10,
    flavor: 'Lo grabado resuena.',
    tags: ['retrigger'],
    retrigger: { when: { type: 'hasEnhancement' }, times: 1 },
  },

  // ---- ×Multiplicador (§11.1.g) ----
  {
    id: 'relic.espejo_negro',
    name: 'Espejo Negro',
    rarity: 'rara',
    cost: 10,
    flavor: 'Refleja mas de lo que muestras.',
    tags: ['xmult'],
    xMult: [{ kind: 'xMult', factor: 1.5 }],
  },
  {
    id: 'relic.eclipse',
    name: 'Eclipse',
    rarity: 'rara',
    cost: 10,
    flavor: 'Apaga el mult, enciende las fichas.',
    tags: ['xmult', 'fichas'],
    xMult: [
      { kind: 'xMult', factor: 0.5 },
      { kind: 'xFichas', factor: 2 },
    ],
  },
  {
    id: 'relic.sistole',
    name: 'Sistole',
    rarity: 'rara',
    cost: 9,
    flavor: 'El primer latido lo es todo.',
    tags: ['xmult'],
    xMult: [{ kind: 'xMult', factor: 3, when: { type: 'firstHand' } }],
  },
  {
    id: 'relic.luna_sangrante',
    name: 'Luna Sangrante',
    rarity: 'rara',
    cost: 9,
    flavor: 'Crece cuando la razon mengua.',
    tags: ['xmult', 'cordura'],
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'sanityBelow', value: 50 } }],
  },
  {
    id: 'relic.convergencia',
    name: 'Convergencia',
    rarity: 'rara',
    cost: 11,
    flavor: 'Cuanto mas se juntan, mas se multiplican.',
    tags: ['xmult'],
    xMult: [{ kind: 'xMult', factor: 1, perStep: { per: 'xmultRelics', step: 0.25 } }],
  },

  // ---- Escaladoras (§11.1.h) ----
  {
    id: 'relic.sanguijuela',
    name: 'Sanguijuela',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Cada pareja la engorda.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'handPlayed', handType: 'pareja' }, add: 1, as: 'mult' },
  },
  {
    id: 'relic.gloton',
    name: 'Gloton',
    rarity: 'rara',
    cost: 9,
    flavor: 'Nunca tiene suficiente.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'cardScored' }, add: 3, as: 'fichas' },
  },
  {
    id: 'relic.vendetta',
    name: 'Vendetta',
    rarity: 'rara',
    cost: 10,
    flavor: 'Cada jefe caido alimenta la siguiente.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'bossDefeated' }, add: 4, as: 'mult' },
  },

  // ---- Cambia-motor (§11.1.i) ----
  {
    id: 'relic.tercera_mano',
    name: 'Tercera Mano',
    rarity: 'rara',
    cost: 10,
    flavor: 'Una mano mas para lo que no se nombra.',
    tags: ['utilidad'],
    modifyCombat: { hands: 1 },
  },
  {
    id: 'relic.quinta_carta',
    name: 'Quinta Carta',
    rarity: 'rara',
    cost: 10,
    flavor: 'Siempre hay sitio para una mas.',
    tags: ['utilidad'],
    modifyCombat: { handSize: 1 },
  },

  // ---- Fichas plano (resto §11.1.b) ----
  {
    id: 'relic.ladrillo',
    name: 'Ladrillo',
    rarity: 'comun',
    cost: 4,
    flavor: 'Solido. Aburrido. Eficaz.',
    tags: ['fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 40 }],
  },
  {
    id: 'relic.ceniza_compacta',
    name: 'Ceniza Compacta',
    rarity: 'comun',
    cost: 4,
    flavor: 'Lo que arde en la mano, se cuenta.',
    tags: ['fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 10, per: 'enhancedCardsInHand' }],
  },
  {
    id: 'relic.piedra_de_amolar',
    name: 'Piedra de Amolar',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Cada filo nuevo la afila a ella.',
    tags: ['fichas', 'escaladora'],
    onHandPlayed: [{ kind: 'addFichas', n: 25 }],
    scaler: { trigger: { on: 'enhanced' }, add: 5, as: 'fichas' },
  },

  // ---- Condicionales por tipo de mano (resto §11.1.d) ----
  {
    id: 'relic.trinidad',
    name: 'Trinidad',
    rarity: 'comun',
    cost: 5,
    flavor: 'Tres en uno.',
    tags: ['mult'],
    onHandPlayed: [{ kind: 'addMult', n: 10, when: { type: 'handType', any: ['trio'] } }],
  },
  {
    id: 'relic.serpiente',
    name: 'Serpiente',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Se desliza en linea recta.',
    tags: ['mult'],
    // +6 con Escalera; +12 mas (una escalera siempre es de 5 cartas en UMBRAL).
    onHandPlayed: [
      {
        kind: 'addMult',
        n: 6,
        when: { type: 'handType', any: ['escalera', 'escalera_color', 'escalera_real'] },
      },
      {
        kind: 'addMult',
        n: 12,
        when: { type: 'handType', any: ['escalera', 'escalera_color', 'escalera_real'] },
      },
    ],
  },
  {
    id: 'relic.banquete',
    name: 'Banquete',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Mesa llena, fichas llenas.',
    tags: ['fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 40, when: { type: 'handType', any: ['full'] } }],
  },

  // ---- Composicion / rango (resto §11.1.e) ----
  {
    id: 'relic.as_en_la_manga',
    name: 'As en la Manga',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Siempre uno mas, escondido.',
    tags: ['fichas', 'mult'],
    onCardScored: [
      { kind: 'addFichas', n: 20, when: { type: 'isAce' } },
      { kind: 'addMult', n: 2, when: { type: 'isAce' } },
    ],
  },

  // ---- Retrigger (resto §11.1.f) ----
  {
    id: 'relic.eco_hueco',
    name: 'Eco Hueco',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'La primera voz vuelve.',
    tags: ['retrigger'],
    retrigger: { when: { type: 'always' }, times: 1, firstOnly: true },
  },
  {
    id: 'relic.resonancia_espectral',
    name: 'Resonancia Espectral',
    rarity: 'espectral',
    cost: 13,
    flavor: 'Lo sellado resuena de mas.',
    tags: ['retrigger', 'espectral'],
    retrigger: { when: { type: 'hasSeal' }, times: 2 },
  },

  // ---- Escaladoras (resto §11.1.h) ----
  {
    id: 'relic.cronica',
    name: 'Cronica',
    rarity: 'rara',
    cost: 9,
    flavor: 'Cada descarte queda escrito.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'discard' }, add: 2, as: 'fichas' },
  },
  {
    id: 'relic.devorador',
    name: 'Devorador',
    rarity: 'espectral',
    cost: 13,
    flavor: 'Engorda con cada perdida.',
    tags: ['escaladora', 'espectral'],
    scaler: { trigger: { on: 'cardDestroyed' }, add: 0.2, as: 'xmult' },
  },

  // ---- Cambia-motor (resto §11.1.i) ----
  {
    id: 'relic.comodin',
    name: 'Comodin',
    rarity: 'rara',
    cost: 11,
    // TODO: la carta-comodin real (elegir rango) necesita targeting (render). Pasivo provisional.
    flavor: 'Es lo que necesites que sea.',
    tags: ['utilidad'],
    onHandPlayed: [{ kind: 'addMult', n: 4 }],
  },
  {
    id: 'relic.igualador',
    name: 'Igualador',
    rarity: 'rara',
    cost: 10,
    flavor: 'Ante el, todas las cartas valen lo mismo.',
    tags: ['fichas'],
    cardChipOverride: 10,
  },
  {
    id: 'relic.memoria',
    name: 'Memoria',
    rarity: 'rara',
    cost: 9,
    // Aproximacion: crece +20 fichas por mano jugada (deberia premiar repetir el mismo tipo).
    flavor: 'Recuerda, y cobra el recuerdo.',
    tags: ['escaladora'],
    scaler: { trigger: { on: 'handPlayed' }, add: 20, as: 'fichas' },
  },

  // ---- Espectrales (§11.1.j) ----
  {
    id: 'relic.ojo_que_no_duerme',
    name: 'Ojo que No Duerme',
    rarity: 'espectral',
    cost: 12,
    flavor: 'Ve la carta que viene. Siempre.',
    tags: ['espectral', 'vidente'],
    onAcquire: { maxCandlesDelta: -1 },
  },
  {
    id: 'relic.simbiosis',
    name: 'Simbiosis',
    rarity: 'espectral',
    cost: 14,
    flavor: 'Cuantas mas sombras, mas fuerza.',
    tags: ['espectral', 'xmult'],
    xMult: [{ kind: 'xMult', factor: 1, perStep: { per: 'spectralRelics', step: 0.5 } }],
  },
  {
    id: 'relic.hambre',
    name: 'Hambre',
    rarity: 'espectral',
    cost: 13,
    flavor: 'Multiplica, pero devora.',
    tags: ['espectral', 'xmult'],
    xMult: [{ kind: 'xMult', factor: 2 }],
    onCombatEnd: { destroyRandomDeck: 1 },
  },
  {
    id: 'relic.reloj_detenido',
    name: 'Reloj Detenido',
    rarity: 'espectral',
    cost: 13,
    flavor: 'El primer instante es eterno; el resto, niebla.',
    tags: ['espectral', 'xmult'],
    xMult: [
      { kind: 'xMult', factor: 3, when: { type: 'firstHand' } },
      { kind: 'xMult', factor: 0.75, when: { type: 'not', cond: { type: 'firstHand' } } },
    ],
  },
  {
    id: 'relic.eco_del_vacio',
    name: 'Eco del Vacio',
    rarity: 'espectral',
    cost: 14,
    flavor: 'En el abismo, todo se dobla.',
    tags: ['espectral', 'xmult', 'cordura'],
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'sanityBelow', value: 20 } }],
  },

  // ---- Malditas (§11.1.k) ----
  {
    id: 'relic.pacto_de_plomo',
    name: 'Pacto de Plomo',
    rarity: 'maldita',
    cost: 15,
    flavor: 'Pesa, pero cumple.',
    tags: ['maldita', 'fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 100 }],
    modifyCombat: { hands: -1 },
  },
  {
    id: 'relic.corona_de_espinas',
    name: 'Corona de Espinas',
    rarity: 'maldita',
    cost: 16,
    flavor: 'Reina y sangra.',
    tags: ['maldita', 'xmult'],
    xMult: [{ kind: 'xMult', factor: 3 }],
    onCombatStart: { sanityDelta: -5 },
  },
  {
    id: 'relic.cadena',
    name: 'Cadena',
    rarity: 'maldita',
    cost: 15,
    // La restriccion de no-vender/descartar reliquias se aplica en la tienda (Bloque 10).
    flavor: 'No la sueltas. Ella no te suelta.',
    tags: ['maldita', 'mult'],
    onHandPlayed: [{ kind: 'addMult', n: 12 }],
  },
  {
    id: 'relic.diezmo',
    name: 'Diezmo',
    rarity: 'maldita',
    cost: 16,
    flavor: 'Paga su parte. Cada vez.',
    tags: ['maldita', 'xmult'],
    xMult: [{ kind: 'xMult', factor: 2 }],
    onUmbralEnd: { goldFactor: 0.8 },
  },
  {
    id: 'relic.sacrificio',
    name: 'Sacrificio',
    rarity: 'maldita',
    cost: 18,
    flavor: 'Mucho poder, a costa del mazo.',
    tags: ['maldita', 'mult'],
    onHandPlayed: [{ kind: 'addMult', n: 20 }],
    onCombatStart: { destroyRandomDeck: 1 },
  },

  // ---- Legendarias (§11.1.l) ----
  {
    id: 'relic.corazon_del_abismo',
    name: 'Corazon del Abismo',
    rarity: 'legendaria',
    cost: 24,
    flavor: 'Late con lo que pierdes.',
    tags: ['legendaria', 'xmult', 'cordura'],
    xMult: [{ kind: 'xMult', factor: 1, perStep: { per: 'corduraLost', step: 0.05 } }],
  },
  {
    id: 'relic.el_contable_perfecto',
    name: 'El Contable Perfecto',
    rarity: 'legendaria',
    cost: 26,
    flavor: 'No se le escapa una moneda.',
    tags: ['legendaria', 'economia', 'fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 1, per: 'gold' }],
  },
  {
    id: 'relic.caleidoscopio',
    name: 'Caleidoscopio',
    rarity: 'legendaria',
    cost: 24,
    flavor: 'Cada carta es del palo que mas te convenga.',
    tags: ['legendaria', 'palo'],
    wildSuit: true,
  },
  {
    id: 'relic.eternidad',
    name: 'Eternidad',
    rarity: 'legendaria',
    cost: 26,
    flavor: 'Lo que resuena, resuena una vez mas.',
    tags: ['legendaria', 'retrigger'],
    extraRetriggerPerSource: 1,
  },
  {
    id: 'relic.el_coleccionista_supremo',
    name: 'El Coleccionista Supremo',
    rarity: 'legendaria',
    cost: 26,
    flavor: 'Todo el mazo puntua, este o no en la mano.',
    tags: ['legendaria', 'fichas'],
    onHandPlayed: [{ kind: 'addFichas', n: 5, per: 'deckCards' }],
  },
  {
    id: 'relic.sin_fondo',
    name: 'Sin Fondo',
    rarity: 'legendaria',
    cost: 24,
    flavor: 'No hay tope. Cuidado.',
    tags: ['legendaria', 'retrigger'],
    noRetriggerCap: true,
    onAcquire: { maxCandlesDelta: -1 },
  },
];
