// Reliquias de Recipiente (§8): 1 inicial + 5 exclusivas por Recipiente = 36. Como DATA.
// Algunas mecanicas tematicas (scry, gasto en tienda, alucinaciones) se aproximan con el DSL
// y se afinan cuando lleguen sus sistemas (Bloques 10/18); marcadas con TODO.
import type { RelicDef } from '@umbral/engine';

export const VESSEL_RELICS: RelicDef[] = [
  // ===== HERALDO =====
  {
    id: 'relic.heraldo.estandarte',
    name: 'Estandarte',
    rarity: 'comun',
    cost: 5,
    flavor: 'Crece con cada paso del descenso.',
    tags: ['mult'],
    vessel: 'heraldo',
    onHandPlayed: [
      { kind: 'addMult', n: 2 },
      { kind: 'addMult', n: 1, per: 'bossesDefeated' },
    ],
  },
  {
    id: 'relic.heraldo.heraldo_de_hierro',
    name: 'Heraldo de Hierro',
    rarity: 'rara',
    cost: 9,
    flavor: 'La repeticion forja.',
    tags: ['fichas'],
    vessel: 'heraldo',
    onHandPlayed: [{ kind: 'addFichas', n: 10 }],
  },
  {
    id: 'relic.heraldo.voz_del_heraldo',
    name: 'Voz del Heraldo',
    rarity: 'rara',
    cost: 10,
    // TODO: deberia hacer que el Eco de +2 (modifica mecanica del Recipiente).
    flavor: 'El eco responde mas fuerte.',
    tags: ['mult'],
    vessel: 'heraldo',
    onHandPlayed: [{ kind: 'addMult', n: 2 }],
  },
  {
    id: 'relic.heraldo.marcha',
    name: 'Marcha',
    rarity: 'rara',
    cost: 11,
    flavor: 'Un paso mas, siempre.',
    tags: ['utilidad'],
    vessel: 'heraldo',
    modifyCombat: { hands: 1 },
  },
  {
    id: 'relic.heraldo.pendon_roto',
    name: 'Pendon Roto',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Cada tipo nuevo ondea.',
    tags: ['mult'],
    vessel: 'heraldo',
    onHandPlayed: [{ kind: 'addMult', n: 3 }],
  },
  {
    id: 'relic.heraldo.trompeta',
    name: 'Trompeta',
    rarity: 'rara',
    cost: 10,
    flavor: 'La primera nota lo es todo.',
    tags: ['xmult'],
    vessel: 'heraldo',
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'firstHand' } }],
  },

  // ===== VIDENTE =====
  {
    id: 'relic.vidente.tercer_ojo',
    name: 'Tercer Ojo',
    rarity: 'pococomun',
    cost: 6,
    // TODO: +30 fichas al jugar la carta del tope visible (requiere scry/render).
    flavor: 'Ve venir lo que cuenta.',
    tags: ['fichas', 'vidente'],
    vessel: 'vidente',
    onHandPlayed: [{ kind: 'addFichas', n: 20 }],
  },
  {
    id: 'relic.vidente.augur',
    name: 'Augur',
    rarity: 'pococomun',
    cost: 7,
    flavor: 'Entierra lo que no quieres ver.',
    tags: ['vidente', 'mult'],
    vessel: 'vidente',
    onHandPlayed: [{ kind: 'addMult', n: 2 }],
  },
  {
    id: 'relic.vidente.carta_marcada',
    name: 'Carta Marcada',
    rarity: 'rara',
    cost: 9,
    flavor: 'La que viste venir, golpea mas.',
    tags: ['vidente', 'mult'],
    vessel: 'vidente',
    onHandPlayed: [{ kind: 'addMult', n: 4 }],
  },
  {
    id: 'relic.vidente.hilo_del_destino',
    name: 'Hilo del Destino',
    rarity: 'rara',
    cost: 11,
    flavor: 'Tres hilos previstos, un nudo.',
    tags: ['vidente', 'xmult'],
    vessel: 'vidente',
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'exactlyCards', count: 3 } }],
  },
  {
    id: 'relic.vidente.ojo_abierto',
    name: 'Ojo Abierto',
    rarity: 'espectral',
    cost: 12,
    flavor: 'Ves cinco. A cambio de luz.',
    tags: ['vidente', 'espectral'],
    vessel: 'vidente',
    onAcquire: { maxCandlesDelta: -1 },
  },
  {
    id: 'relic.vidente.reescritura',
    name: 'Reescritura',
    rarity: 'rara',
    cost: 9,
    flavor: 'Ordena la mano a tu favor.',
    tags: ['vidente', 'mult'],
    vessel: 'vidente',
    onHandPlayed: [{ kind: 'addMult', n: 3 }],
  },

  // ===== USURERO =====
  {
    id: 'relic.usurero.libro_de_cuentas',
    name: 'Libro de Cuentas',
    rarity: 'pococomun',
    cost: 6,
    // TODO: interes sin tope (Bloque 10 economia). +1 ficha por moneda mientras tanto.
    flavor: 'Cada cifra cuadra.',
    tags: ['economia', 'fichas'],
    vessel: 'usurero',
    onHandPlayed: [{ kind: 'addFichas', n: 1, per: 'gold' }],
  },
  {
    id: 'relic.usurero.prestamo_usurario',
    name: 'Prestamo Usurario',
    rarity: 'rara',
    cost: 11,
    flavor: 'El capital se multiplica solo.',
    tags: ['economia', 'xmult'],
    vessel: 'usurero',
    xMult: [{ kind: 'xMult', factor: 1, perStep: { per: 'gold', step: 0.04 } }],
  },
  {
    id: 'relic.usurero.cofre_sin_fondo',
    name: 'Cofre Sin Fondo',
    rarity: 'rara',
    cost: 9,
    // TODO: -10 oro al entrar a cada Umbral (Bloque 10). +50 al obtenerlo.
    flavor: 'Lleno, pero con fugas.',
    tags: ['economia'],
    vessel: 'usurero',
    onAcquire: { goldDelta: 50 },
  },
  {
    id: 'relic.usurero.avaricia',
    name: 'Avaricia',
    rarity: 'rara',
    cost: 9,
    // TODO: no puedes vender; todo cuesta -40% (tienda, Bloque 10).
    flavor: 'No suelta una sola moneda.',
    tags: ['economia'],
    vessel: 'usurero',
    onHandPlayed: [{ kind: 'addFichas', n: 15 }],
  },
  {
    id: 'relic.usurero.moneda_de_hueso',
    name: 'Moneda de Hueso',
    rarity: 'rara',
    cost: 10,
    // TODO: +2 fichas perm por moneda gastada (tienda, Bloque 10).
    flavor: 'Pagas con lo que eres.',
    tags: ['economia', 'fichas'],
    vessel: 'usurero',
    onHandPlayed: [{ kind: 'addFichas', n: 1, per: 'gold' }],
  },
  {
    id: 'relic.usurero.inversion',
    name: 'Inversion',
    rarity: 'rara',
    cost: 11,
    // TODO: duplica monedas al fin de Umbral si no compraste (Bloque 10).
    flavor: 'Quien no gasta, acumula.',
    tags: ['economia'],
    vessel: 'usurero',
    onHandPlayed: [{ kind: 'addFichas', n: 1, per: 'gold' }],
  },

  // ===== COLECCIONISTA =====
  {
    id: 'relic.coleccionista.vitrina',
    name: 'Vitrina',
    rarity: 'pococomun',
    cost: 6,
    // TODO: deberia contar las mejoras del MAZO; aproximado a las de la mano.
    flavor: 'Expone lo mejorado.',
    tags: ['fichas'],
    vessel: 'coleccionista',
    onHandPlayed: [{ kind: 'addFichas', n: 10, per: 'enhancedCardsInHand' }],
  },
  {
    id: 'relic.coleccionista.conservador',
    name: 'Conservador',
    rarity: 'rara',
    cost: 9,
    // TODO: los Cristal nunca se quiebran (Bloque 10).
    flavor: 'Nada se rompe bajo su cuidado.',
    tags: ['utilidad'],
    vessel: 'coleccionista',
    onHandPlayed: [{ kind: 'addFichas', n: 20 }],
  },
  {
    id: 'relic.coleccionista.especimen_raro',
    name: 'Especimen Raro',
    rarity: 'rara',
    cost: 10,
    flavor: 'Las piezas mejoradas valen mas.',
    tags: ['fichas'],
    vessel: 'coleccionista',
    onCardScored: [{ kind: 'addFichas', n: 20, when: { type: 'hasEnhancement' } }],
  },
  {
    id: 'relic.coleccionista.coleccion_completa',
    name: 'Coleccion Completa',
    rarity: 'rara',
    cost: 12,
    flavor: 'Cuando todo encaja, todo se dobla.',
    tags: ['xmult'],
    vessel: 'coleccionista',
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'atLeastCards', count: 5 } }],
  },
  {
    id: 'relic.coleccionista.restaurador',
    name: 'Restaurador',
    rarity: 'rara',
    cost: 9,
    // TODO: copia una mejora a otra carta 1/Umbral (Bloque 10).
    flavor: 'Devuelve el brillo perdido.',
    tags: ['utilidad'],
    vessel: 'coleccionista',
    onHandPlayed: [{ kind: 'addFichas', n: 15 }],
  },
  {
    id: 'relic.coleccionista.pieza_de_museo',
    name: 'Pieza de Museo',
    rarity: 'rara',
    cost: 11,
    flavor: 'La joya de la coleccion.',
    tags: ['fichas'],
    vessel: 'coleccionista',
    onHandPlayed: [{ kind: 'addFichas', n: 30, when: { type: 'handHasFigure' } }],
  },

  // ===== BESTIA =====
  {
    id: 'relic.bestia.colmillo',
    name: 'Colmillo',
    rarity: 'pococomun',
    cost: 6,
    flavor: 'Cada descarte lo afila.',
    tags: ['escaladora'],
    vessel: 'bestia',
    scaler: { trigger: { on: 'discard' }, add: 1, as: 'fichas' },
  },
  {
    id: 'relic.bestia.hambre_voraz',
    name: 'Hambre Voraz',
    rarity: 'rara',
    cost: 10,
    // TODO: el Frenesi deberia dar +2 por punto (modifica mecanica).
    flavor: 'Nunca se sacia.',
    tags: ['mult'],
    vessel: 'bestia',
    onHandPlayed: [{ kind: 'addMult', n: 2 }],
  },
  {
    id: 'relic.bestia.mandibula',
    name: 'Mandibula',
    rarity: 'rara',
    cost: 9,
    flavor: 'Cierra fuerte sobre lo descartado.',
    tags: ['escaladora'],
    vessel: 'bestia',
    scaler: { trigger: { on: 'discard' }, add: 3, as: 'fichas' },
  },
  {
    id: 'relic.bestia.instinto',
    name: 'Instinto',
    rarity: 'rara',
    cost: 10,
    flavor: 'Sin pensar, golpea primero.',
    tags: ['xmult'],
    vessel: 'bestia',
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'firstHand' } }],
  },
  {
    id: 'relic.bestia.rastro_de_sangre',
    name: 'Rastro de Sangre',
    rarity: 'rara',
    cost: 9,
    // TODO: carta destruida -> +1 descarte este combate (Bloque 12).
    flavor: 'Sigue el rastro hasta el final.',
    tags: ['escaladora'],
    vessel: 'bestia',
    scaler: { trigger: { on: 'cardDestroyed' }, add: 2, as: 'fichas' },
  },
  {
    id: 'relic.bestia.saciedad',
    name: 'Saciedad',
    rarity: 'rara',
    cost: 11,
    flavor: 'Lo que sobra, se acumula.',
    tags: ['escaladora'],
    vessel: 'bestia',
    scaler: { trigger: { on: 'handPlayed' }, add: 1, as: 'mult' },
  },

  // ===== PROFANO =====
  {
    id: 'relic.profano.sello_roto',
    name: 'Sello Roto',
    rarity: 'espectral',
    cost: 12,
    flavor: 'Cada grieta de cordura suma.',
    tags: ['espectral', 'mult', 'cordura'],
    vessel: 'profano',
    onHandPlayed: [{ kind: 'addMult', n: 0.2, per: 'corduraLost' }], // +1 mult por cada 5 perdidos
  },
  {
    id: 'relic.profano.voz_interior',
    name: 'Voz Interior',
    rarity: 'espectral',
    cost: 13,
    flavor: 'Habla mas claro cuanto peor estas.',
    tags: ['espectral', 'xmult', 'cordura'],
    vessel: 'profano',
    xMult: [{ kind: 'xMult', factor: 2, when: { type: 'sanityBelow', value: 30 } }],
  },
  {
    id: 'relic.profano.ofrenda',
    name: 'Ofrenda',
    rarity: 'espectral',
    cost: 13,
    // TODO: sacrifica 10 cordura -> +1 reliquia espectral (evento/Santuario, Bloque 12).
    flavor: 'Da, para recibir.',
    tags: ['espectral', 'mult'],
    vessel: 'profano',
    onHandPlayed: [{ kind: 'addMult', n: 6 }],
  },
  {
    id: 'relic.profano.abismo',
    name: 'Abismo',
    rarity: 'maldita',
    cost: 16,
    // TODO: anula la penalizacion de Malditas a cambio de cordura (Bloque 10).
    flavor: 'El fondo no penaliza; consume.',
    tags: ['maldita', 'mult'],
    vessel: 'profano',
    onCombatStart: { sanityDelta: -3 },
    onHandPlayed: [{ kind: 'addMult', n: 8 }],
  },
  {
    id: 'relic.profano.susurro',
    name: 'Susurro',
    rarity: 'espectral',
    cost: 13,
    // TODO: alucinacion jugada como real -> +50 fichas (Bloque 18).
    flavor: 'Lo que no esta, tambien cuenta.',
    tags: ['espectral', 'fichas'],
    vessel: 'profano',
    onHandPlayed: [{ kind: 'addFichas', n: 30 }],
  },
  {
    id: 'relic.profano.disolucion',
    name: 'Disolucion',
    rarity: 'maldita',
    cost: 18,
    // TODO: con 0 cordura no mueres; -1 vela/combate (Bloque 18). ×4 con cordura al limite.
    flavor: 'En el limite, el poder roto.',
    tags: ['maldita', 'xmult', 'cordura'],
    vessel: 'profano',
    xMult: [{ kind: 'xMult', factor: 4, when: { type: 'sanityBelow', value: 1 } }],
  },
];
