// Vales (§11.5): mejoras PERMANENTES del run. No ocupan slot; se compran en tienda.
import type { VoucherDef } from '@umbral/engine';

export const VOUCHERS: VoucherDef[] = [
  {
    id: 'vale.reroll',
    name: 'Vale del Reroll',
    cost: 6,
    flavor: 'Rerolls mas baratos.',
    effect: { rerollDiscount: 1 },
  },
  {
    id: 'vale.mercader',
    name: 'Vale del Mercader',
    cost: 10,
    flavor: 'Todo en tienda -15%.',
    effect: { shopDiscount: 0.15 },
  },
  {
    id: 'vale.abundancia',
    name: 'Vale de la Abundancia',
    cost: 10,
    flavor: '+1 articulo en cada tienda.',
    effect: { flags: ['abundancia'] },
  },
  {
    id: 'vale.mano',
    name: 'Vale de la Mano',
    cost: 12,
    flavor: '+1 mano por combate.',
    effect: { hands: 1 },
  },
  {
    id: 'vale.descarte',
    name: 'Vale del Descarte',
    cost: 10,
    flavor: '+1 descarte por combate.',
    effect: { discards: 1 },
  },
  {
    id: 'vale.carta',
    name: 'Vale de la Carta',
    cost: 12,
    flavor: '+1 carta en mano.',
    effect: { handSize: 1 },
  },
  {
    id: 'vale.reliquia',
    name: 'Vale de la Reliquia',
    cost: 12,
    flavor: '+1 slot de reliquia.',
    effect: { relicSlots: 1 },
  },
  {
    id: 'vale.arcano',
    name: 'Vale del Arcano',
    cost: 10,
    flavor: '+1 slot de arcano.',
    effect: { consumableSlots: 1 },
  },
  {
    id: 'vale.suerte',
    name: 'Vale de la Suerte',
    cost: 11,
    flavor: 'Mejores rarezas en ofertas.',
    effect: { flags: ['suerte'] },
  },
  {
    id: 'vale.vela',
    name: 'Vale de la Vela',
    cost: 12,
    flavor: '+1 vela maxima.',
    effect: { maxCandles: 1 },
  },
  {
    id: 'vale.cordura',
    name: 'Vale de la Cordura',
    cost: 10,
    flavor: 'Cordura maxima +20.',
    effect: { maxSanity: 20 },
  },
  {
    id: 'vale.interes',
    name: 'Vale del Interes',
    cost: 9,
    flavor: 'Tope de interes +5.',
    effect: { flags: ['interes'] },
  },
  {
    id: 'vale.vidente',
    name: 'Vale del Vidente',
    cost: 8,
    flavor: 'Ves siempre 1 carta superior.',
    effect: { flags: ['vidente'] },
  },
  {
    id: 'vale.fortuna',
    name: 'Vale de la Fortuna',
    cost: 11,
    flavor: 'El draft siempre incluye 1 reliquia.',
    effect: { flags: ['fortuna'] },
  },
  {
    id: 'vale.profundidad',
    name: 'Vale de la Profundidad',
    cost: 12,
    flavor: 'Reduce el escalado de Infinito un 10%.',
    effect: { flags: ['profundidad'] },
  },
];
